services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    env_file: ../.env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: walletpass
      POSTGRES_DB: wallet_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

volumes:
  pgdata: