name: wallet-app

services:
  api:
    container_name: wallet-app-api
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file: ../.env
    depends_on:
      - postgres

  postgres:
    container_name: wallet-app-postgres
    image: postgres:15
    environment:
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: walletpass
      POSTGRES_DB: wallet_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  pgdata: